# Author: James Ashmore
# Copyright: Copyright 2020, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

pepfile: "config/project_config.yaml"

pepschema: "schemas/pep.schema.yaml"

include: "rules/common.smk"
include: "rules/cutadapt.smk"
include: "rules/genomepy.smk"
include: "rules/gffread.smk"
include: "rules/kallisto.smk"
include: "rules/star.smk"
include: "rules/sambamba.smk"
include: "rules/tximport.smk"
include: "rules/deseq2.smk"
include: "rules/plots.smk"
include: "rules/rseqc.smk"
include: "rules/rsubread.smk"
include: "rules/edger.smk"
include: "rules/limma.smk"
include: "rules/deeptools.smk"
include: "rules/consensus.smk"

output = Output(pep.sample_table, pep.subsample_table)

rule all:
    input:
        output.kallisto_index(),
        output.kallisto_quant(),
        output.star_index(),
        output.star_align(),
        output.rsubread_featurecounts(),
        output.deseq2_init(),
        output.deseq2_counts(),
        output.deseq2_normcounts(),
        output.deseq2_logcounts(),
        output.deseq2_results(),
        output.edger_init(),
        output.edger_counts(),
        output.edger_normcounts(),
        output.edger_logcounts(),
        output.edger_results(),
        output.limma_counts(),
        output.limma_normcounts(),
        output.limma_logcounts(),
        output.limma_results(),
        output.plot_corr(),
        output.plot_dist(),
        output.plot_prcomp(),
        output.plot_cmdscale(),
        output.plot_diff(),
        output.plot_pvalue(),
        output.plot_volcano(),
        output.plot_heatmap(),
        output.bam_coverage()
