# Author: James Ashmore
# Copyright: Copyright 2020, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

configfile: "config/config.yaml"
            
include: "rules/project.smk"
project = Project(config)

include: "rules/common.smk"
include: "rules/fastq.smk"
include: "rules/fastqc.smk"
include: "rules/cutadapt.smk"
include: "rules/genomepy.smk"
include: "rules/gffread.smk"
include: "rules/star.smk"
include: "rules/kallisto.smk"
include: "rules/tximport.smk"
include: "rules/deseq2.smk"
include: "rules/edger.smk"
include: "rules/goseq.smk"

wildcard_constraints:
    sample = "|".join(project.samples["sample"]),
    unit = "|".join(project.units["unit"])

rule all:
    input:
        project.fastq_output(),
        project.fastqc_output(),
        project.cutadapt_output(),
        project.genomepy_output(),
        project.gffread_output(),
        project.tximport_output(),
        project.deseq2_output()
