# Author: James Ashmore
# Copyright: Copyright 2020, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

configfile: "config/config.yaml"

include: "rules/project.smk"
include: "rules/fastq.smk"
include: "rules/fastqc.smk"
include: "rules/cutadapt.smk"
include: "rules/genomepy.smk"
include: "rules/gffread.smk"
include: "rules/kallisto.smk"

project = Project(config)

wildcard_constraints:
    sample = "|".join(project.samples["sample"]),
    unit = "|".join(project.units["unit"])

rule all:
    input:
        project.fastq_output(),
        project.fastqc_output(),
        project.cutadapt_output(),
        project.genomepy_output(),
        project.gffread_output()
