name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-deseq2
  - bioconductor-dupradar
  - bioconductor-edger
  - bioconductor-limma
  - bioconductor-rhdf5
  - bioconductor-rsubread
  - bioconductor-tximport
  - r-ggplot2
  - r-ggrepel
  - r-magick
  - r-pheatmap
  - r-scales
  - cutadapt
  - fastqc
  - genomepy
  - gffread
  - kallisto
  - multiqc
  - pandas
  - qualimap
  - rseqc
  - samtools
  - subread
  - star