# Author: James Ashmore
# Copyright: Copyright 2020, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

samples: "config/samples.csv"
units: "config/units.csv"
genome: "hg19"
contrasts:
  condition_GBR_vs_YRI: {"A": "GBR", "B": "YRI"}

txome:
  source: "UCSC"
  organism: "Homo sapiens"
  release: "release"
  genome: "hg19"
  fasta: "fasta"
  gtf: "fgtf"
